# The URL the site will be built for
base_url = "https://thanhnc.id.vn"

title = "JakeClark - Nguy·ªÖn Ch√≠ Th√†nh"
default_language = "vi"
theme = "tabi"

compile_sass = true
build_search_index = false
generate_feeds = true

taxonomies = [{ name = "tags", feed = true }]

[languages.en]
title = "JakeClark - Nguy·ªÖn Ch√≠ Th√†nh"
taxonomies = [{ name = "tags", feed = true }]
build_search_index = false
generate_feeds = true

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]
skin = "mint"
stylesheets = ["custom.css"]
theme_switcher = true
default_theme = ""
browser_theme_color = "#087e96"
compact_tags = true
favicon_emoji = "üõ†Ô∏è"
socials = [
    { name = "email", url = "mailto:nguyenchithanh210904@gmail.com", icon = "email" },
    { name = "github", url = "https://github.com/JakeClark-chan", icon = "github" },
    { name = "linkedin", url = "https://www.linkedin.com/in/ngchithanh", icon = "linkedin" },
    { name = "facebook", url = "https://facebook.com/nguyenchithanh21", icon = "facebook" },
    { name = "telegram", url = "https://t.me/jakeclark38a", icon = "telegram" },
]
menu = [
    { name = "projects", url = "projects" },
    { name = "faq", url = "faq" },
    { name = "blog", url = "https://blog.thanhnc.id.vn" },
]
footer_menu = [
    { name = "projects", url = "projects" },
    { name = "faq", url = "faq" },
    { name = "blog", url = "https://blog.thanhnc.id.vn" },
]